[WFLY-8599] Create test cases for Elytron Role Mappers
wildfly-security-incubator/wildfly pull request #186
Opened 2017-04-19 13:17 UTC by olukas

https://issues.jboss.org/browse/WFLY-8599
https://issues.jboss.org/browse/JBEAP-10429

2017-04-26 12:44 UTC, kwart requested changes

2017-04-26 12:44 UTC, kwart commented on testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/rolemappers/AddPrefixRoleMapperTestCase.java
> +    public static class ServerSetup extends RoleMapperSetupTask {
It comes to me, that the abstract `RoleMapperSetupTask` doesn't bring any useful feature into the tests. Moreover, it doesn't take care about server reloads (in `tearDown`).

What about to use the `AbstractElytronSetupTask` directly and rewrite the configuration to something like:

```java
        @Override
        protected ConfigurableElement[] getConfigurableElements() {
            List<ConfigurableElement> elements = new ArrayList<>();

            elements.add(new ConfigurableElement() {               
                @Override
                public void create(CLIWrapper cli) throws Exception {
                    cli.sendLine(String.format("/subsystem=elytron/add-prefix-role-mapper=%s:add(prefix=%s)",
                            ADD_PREFIX_MAPPER, ROLE_PREFIX));
                }

                @Override
                public void remove(CLIWrapper cli) throws Exception {
                    cli.sendLine(String.format("/subsystem=elytron/add-prefix-role-mapper=%s:remove()",
                            ADD_PREFIX_MAPPER));
                }

                @Override
                public String getName() {
                    return "rolemappers";
                }
            });
            
            elements.add(PropertiesRealm.builder().withName(PROPERTIES_REALM_NAME)
                    .withUser(USER_WITHOUT_ROLES, PASSWORD)
                    .withUser(USER_WITH_ROLE1, PASSWORD, ROLE1)
                    .withUser(USER_WITH_TWO_ROLES, PASSWORD, ROLE1, ROLE2)
                    .build());
            addSecurityDomainWithRoleMapper(elements, ADD_PREFIX_MAPPER);

            return elements.toArray(new ConfigurableElement[elements.size()]);
        }
```
Or use just some single-purpose `ConfigurationElement` implementation, which will help you little bit (e.g. by implementing `getName()` with a hardcoded value or by repeating some constant values for you). You don't need to share them.  E.g.:

```java
            elements.add(new AddPrefixRoleMappers(
                    String.format("%s:add(prefix=%s)", ADD_PREFIX_MAPPER1, ROLE_PREFIX1),
                    String.format("%s:add(prefix=%s)", ADD_PREFIX_MAPPER2, ROLE_PREFIX2)
                    ));


    public static class AddPrefixRoleMappers implements ConfigurableElement  {

        private final String[] dynamicSuffixes;

        public AddPrefixRoleMappers(String... dynamicSuffixes) {
            this.dynamicSuffixes = dynamicSuffixes;
        }

        @Override
        public void create(CLIWrapper cli) throws Exception {
            for (String sfx : dynamicSuffixes) {
                cli.sendLine("/subsystem=elytron/add-prefix-role-mapper=" + sfx);
            }
        }

        @Override
        public void remove(CLIWrapper cli) throws Exception {
            for (String sfx : dynamicSuffixes) {
                int opIdx = sfx.indexOf(':');
                String newSfx = sfx.substring(0, opIdx + 1) + "remove()";
                cli.sendLine("/subsystem=elytron/add-prefix-role-mapper=" + newSfx);
            }
        }

        @Override
        public String getName() {
            return "add-prefix-role-mapper(s)";
        }
    }

```

2017-04-27 13:18 UTC, olukas commented
@kwart Fixed. Thanks.

2017-04-27 13:20 UTC, kwart approved these changes

2017-04-27 14:46 UTC, kabir approved these changes
Approving paperwork

2017-04-28 15:00 UTC, merged