[WFLY-8613] Create test case for Elytron Aggregate Realm
wildfly-security-incubator/wildfly pull request #193
Opened 2017-04-21 05:24 UTC by olukas

2017-04-26 11:38 UTC, kwart requested changes

2017-04-26 11:38 UTC, kwart commented on testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/AggregateRealmTestCase.java
> +            }
Maybe `ServerReload.reloadIfRequired()` would be safer here.

2017-04-26 11:41 UTC, kwart commented on testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/AggregateRealmTestCase.java
> +            ServerReload.reloadIfRequired(mc.getControllerClient());
Move this call just after the 2nd call of `removeAggregateRealmAndRelatedResources` method in the `tearDown`. IMO, it's not necessary to do it for every single aggregate realm.

2017-04-26 12:24 UTC, olukas commented
@kwart Fixed. Thanks

2017-04-26 12:53 UTC, kwart approved these changes

2017-04-27 14:47 UTC, kabir approved these changes
Approving paperwork

2017-04-28 15:00 UTC, merged