[WFLY-7764] - Elytron JACC Integration
wildfly-security-incubator/wildfly pull request #91
Opened 2017-02-14 16:59 UTC by pedroigor

2017-02-14 17:38 UTC, darranl requested changes
Main thing missing is we will need a transformer for the new attribute in the security subsystem, if set to anything other than the default value we need to reject it.

2017-02-14 17:52 UTC, fjuma commented on ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponentDescription.java
> +    public void setKnownSecurityDomainPredicate(final Function<String, ApplicationSecurityDomainConfig> knownSecurityDomain) {
Just a minor nit, this method should probably be renamed to "setKnownSecurityDomainFunction" now.

2017-02-14 17:53 UTC, fjuma commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/ApplicationSecurityDomainDefinition.java
> +    Function<String, ApplicationSecurityDomainConfig> getKnownSecurityDomainPredicate() {
Same minor nit here, should probably rename this to "getKnownSecurityDomainFunction" now.

2017-02-14 18:23 UTC, fjuma commented on ejb3/src/main/java/org/jboss/as/ejb3/security/JaccInterceptor.java
> +        this.contextID = contextID;
One thing to note is that the EJB subsystem currently contains another interceptor that also sets the policy context id (org.jboss.as.ejb3.security.PolicyContextIdInterceptor). May be able to remove that one now.

2017-02-14 19:02 UTC, pedroigor commented on ejb3/src/main/java/org/jboss/as/ejb3/security/JaccInterceptor.java
> +        this.contextID = contextID;
Yes. Let me check if we can remove it.

2017-02-14 19:16 UTC, pedroigor commented on ejb3/src/main/java/org/jboss/as/ejb3/security/JaccInterceptor.java
> +        this.contextID = contextID;
@fjuma We need that interceptor, but it seems we can remove some code from the new {{JaccInterceptor}} and avoid setting the context id twice. I'm going to perform some tests and see if that is OK.

2017-02-22 21:49 UTC, stuartwdouglas commented
Just FYI JACC does already pass (due to https://github.com/wildfly-security-incubator/wildfly/commit/803ec8c719a7753303afbb85ae31f1b0464221f1 which this is conflicting with), although the changes in the interceptor look like they will be necessary to get role mapping to work.

2017-02-23 20:50 UTC, darranl commented
I have merged the interceptor commit so now going to close this PR as the conflict is duplication.

2017-02-23 20:50 UTC, closed without merging